site_name: Polygon ID Documentation tutorials

site_url: https://polygon.technology/polygon-id/
theme:
  name: material
  palette:
    primary: deep purple
  logo: logo-white.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


nav:
  - Issuer:
    - Overview: "issuer/issuer-overview.md"
    - Iden3 Core:  
      - Introduction: "getting-started/getting-started.md"
      - Core Components:
        - Baby Jubjub Keypair: "getting-started/babyjubjub.md"
        - Sparse Merkle Tree: "getting-started/mt.md"
        - Claim: 
          - Generic Claim: "getting-started/claim/generic-claim.md"
          - Auth Claim: "getting-started/claim/auth-claim.md"
          - Claim Schema: "getting-started/claim/claim-schema.md"
        - Identity: 
          - Identity Structure: "getting-started/identity/identity-structure.md"
          - Identity State: "getting-started/identity/identity-state.md"
          - Identifier: "getting-started/identity/identifier.md"
      - Issue Claim: 
        - Overview: "getting-started/issue-claim-overview.md"
        - via Signature: "getting-started/signature-claim/signature.md"
        - via Merkle Tree: 
          - Intro to State Transition: "getting-started/state-transition/state-transition.md"
          - Add Claim to the Claims Tree: "getting-started/state-transition/new-identity-state.md"
          - Generate Proof for State Transition: "getting-started/state-transition/state-transition-proof.md"
          - Verify the Proof On-Chain: "getting-started/state-transition/on-chain-state-transition.md"
  - Verifier:
    - Overview: "verifier/verifier-overview.md"
    - Verification Library:
      - Introduction: "verifier/verification-library/verifier-library-intro.md"
      - APIs: 
        - Config: "verifier/verification-library/config.md"
        - Auth Request: "verifier/verification-library/request-api-guide.md"
        - Verification: "verifier/verification-library/verification-api-guide.md"
        - ZK Query Language : "verifier/verification-library/zk-query-language.md"
      - Run a Verifier: "verifier/verification-library/verifier-set-up.md"
      - JWZ: "verifier/verification-library/jwz.md"
  - Wallet: 
    - Overview: "wallet/wallet-overview.md"
    - Wallet SDK: 
      - All About Flutter SDK: "wallet/wallet-sdk/flutter-plugin-sdk.md"
      - Polygon SDK Example App: "wallet/wallet-sdk/polygonid-sdk-example-app.md"
      - Polygon SDK Plugin: "wallet/wallet-sdk/polygonid-sdk-plugin.md"
    - Wallet SDK Core Functionality: 
      - Identity Wallet:
        - Create Identity: "wallet/wallet-sdk-core-functionality/identity-wallet/create-identity.md"
        - Sign and Authenticate: "wallet/wallet-sdk-core-functionality/identity-wallet/sign-and-authenticate.md"
      - Credential Wallet: 
        - Fetch and Save Claims: "wallet/wallet-sdk-core-functionality/credential-wallet/fetch-and-save-claims.md"
      - Proof Generation:
        - Overview: "wallet/wallet-sdk-core-functionality/proof-generation/overview.md"
        - Types of Requests and Proofs: "wallet/wallet-sdk-core-functionality/proof-generation/types-of-auth-requests-and-proofs.md"
        - JWZ: "wallet/wallet-sdk-core-functionality/proof-generation/jwz.md"
  - Circuits:
    - Main Circuits: "circuits/main-circuits.md"
    - Template Circuits: "circuits/template-circuits.md"
  - Contracts: 
    - Overview: "contracts/overview.md"
  


# If you declare plugins, you need to declare all of them, 
# including search (which would otherwise have been installed by default.)
plugins:
  - search
  - mermaid2
