site_name: Polygon ID Documentation tutorials

site_url: https://polygon.technology/polygon-id/
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: deep purple
  logo: logo-white.svg
  # favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
    - content.code.copy
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: "index.md"
  - Issuer:
    - Overview: "issuer/issuer-overview.md"
    - Issuer Node Core API: 
      - Overview: "issuer/issuer-core.md"
      - Setup Guide (Core API): "issuer/setup-issuer-core.md"
      - API Reference: 
        - Introduction: "issuer-node/issuer-node-api/introduction.md"
        - API Reference:
          - Identity: "issuer-node/issuer-node-api/identity/apis.md"
          - Claim: "issuer-node/issuer-node-api/claim/apis.md"
          - Agent: "issuer-node/issuer-node-api/agent/apis.md"
    - Issuer Node UI: 
      - Overview: "issuer/issuer-node-ui.md"
      - Setup Guide (API UI): "issuer/setup-issuer-ui.md" 
      - Issuer Node UI Guide: "issuer-node/issuer-node-guide.md"
    - Schemas:
      - Schema Builder UI: "issuer/schema-builder.md"
      - Create Custom Schemas : "issuer/schema.md"
      - Schema Examples: "issuer/schema-exs.md"
    - Credential Linkage: "contracts/credential-linkage.md"
    - Credential Issuance Methods: "issuer/cred-issue-methods.md"
    - Issue Credentials via CLI: "issuer-node/issue-credential-cli.md"  
    - Source Code: "issuer/source-code.md"   
      
  - Verifier:
      - Overview: "verifier/verifier-overview.md"
      - Quick Start - Demo Verifier: "verifier/demo-verifier.md"
      - Features: "verifier/features.md"
      - Verfier SDK - Off-chain:
          - Introduction: "verifier/verification-library/verifier-library-intro.md"
          - APIs:
              - Config: "verifier/verification-library/config.md"
              - Request APIs: "verifier/verification-library/request-api-guide.md"
              - Verification APIs: "verifier/verification-library/verification-api-guide.md"
          - Tutorial - Run a Verifier: "verifier/verification-library/verifier-set-up.md"
      - Verifier SDK - On-chain:
          - Implement ERC20 zk airdrop in 20 minutes: "verifier/on-chain-verification/overview.md"
      - Query Builder: "verifier/query-builder.md"
      - ZK Query Language: "verifier/verification-library/zk-query-language.md"
  - Wallet:
      - Overview: "wallet/wallet-overview.md"
      - Features: "wallet/features.md"
      - Wallet SDK:
          - Flutter SDK:
              - Overview: "wallet/wallet-sdk/flutter-sdk/flutter-sdk-overview.md"
              - Install Flutter SDK: "wallet/wallet-sdk/flutter-sdk/install-flutter-sdk.md"
              - Build App with SDK: "wallet/wallet-sdk/flutter-sdk/build-app-with-flutter-sdk.md"
          - Polygon ID Wallet SDK:
              - Overview: "wallet/wallet-sdk/polygonid-sdk/polygonid-sdk-overview.md"
              - Polygon ID SDK Plugin: "wallet/wallet-sdk/polygonid-sdk/polygonid-sdk-plugin.md"
              - Example App: "wallet/wallet-sdk/polygonid-sdk/example-app.md"
              - Identity:
                  - Overview: "wallet/wallet-sdk/polygonid-sdk/identity/overview.md"
                  - APIs:
                      - Create Identity: "wallet/wallet-sdk/polygonid-sdk/identity/api/create-identity.md"
                      - Backup Identity: "wallet/wallet-sdk/polygonid-sdk/identity/api/backup-identity.md"
                      - Get DID Identifier: "wallet/wallet-sdk/polygonid-sdk/identity/api/get-did-identifier.md"
                      - Get Identity: "wallet/wallet-sdk/polygonid-sdk/identity/api/get-identity.md"
                      - Get Identities: "wallet/wallet-sdk/polygonid-sdk/identity/api/get-identities.md"
                      - Remove Identity: "wallet/wallet-sdk/polygonid-sdk/identity/api/remove-identity.md"
                      - Restore Identity: "wallet/wallet-sdk/polygonid-sdk/identity/api/restore-identity.md"
                      - Get State: "wallet/wallet-sdk/polygonid-sdk/identity/api/get-state.md"
                      - Sign Message: "wallet/wallet-sdk/polygonid-sdk/identity/api/sign.md"
              - Credential:
                  - Overview: "wallet/wallet-sdk/polygonid-sdk/credential/overview.md"
                  - APIs:
                      - Fetch and Save Claims: "wallet/wallet-sdk/polygonid-sdk/credential/api/fetch-and-save-claims.md"
                      - Get Claims: "wallet/wallet-sdk/polygonid-sdk/credential/api/get-claims.md"
                      - Update Claims: "wallet/wallet-sdk/polygonid-sdk/credential/api/update-claims.md"
                      - Remove Claims: "wallet/wallet-sdk/polygonid-sdk/credential/api/remove-claims.md"
              - Iden3comm:
                  - Overview: "wallet/wallet-sdk/polygonid-sdk/iden3comm/overview.md"
                  - Auth Requests: "wallet/wallet-sdk/polygonid-sdk/iden3comm/auth-requests.md"
                  - JWZ: "wallet/wallet-sdk/polygonid-sdk/iden3comm/jwz.md"
                  - APIs:
                      - Authenticate: "wallet/wallet-sdk/polygonid-sdk/iden3comm/api/authenticate.md"
                      - Get Proof: "wallet/wallet-sdk/polygonid-sdk/iden3comm/api/get-proofs.md"
                      - Get Vocabulary: "wallet/wallet-sdk/polygonid-sdk/iden3comm/api/get-vocabs.md"
                      - Get Iden3 Message: "wallet/wallet-sdk/polygonid-sdk/iden3comm/api/iden3-message.md"
              - Proof:
                  - Overview: "wallet/wallet-sdk/polygonid-sdk/proof/overview.md"
                  - APIs:
                      - Generate Proof: "wallet/wallet-sdk/polygonid-sdk/proof/api/prove.md"
              - Profiles:
                  - Overview: "wallet/wallet-sdk/polygonid-sdk/profiles/overview.md"
                  - Get Profiles: "wallet/wallet-sdk/polygonid-sdk/profiles/api/get-profiles.md"
                  - Add Profile: "wallet/wallet-sdk/polygonid-sdk/profiles/api/add-profile.md"
                  - Remove Profile: "wallet/wallet-sdk/polygonid-sdk/profiles/api/remove-profile.md"
          - Android SDK:
              - Implement Android SDK: "wallet/wallet-sdk/android-sdk/install-android-sdk.md"
              - Example App: "wallet/wallet-sdk/android-sdk/example-app.md"     
  - Smart Contracts:
      - Overview: "contracts/overview.md"

  - JS SDK:
      - Overview: "js-sdk/js-sdk-overview.md"
      - Components:
          - Identity:
              - Identity Wallet: "js-sdk/js-sdk-components/identity/identity-wallet.md"
          - Credential:
              - Credential Wallet: "js-sdk/js-sdk-components/credential/credential-wallet.md"
          - Iden3comm:
              - Iden3comm: "js-sdk/js-sdk-components/iden3comm/iden3comm.md"
          - Proof:
              - Proof: "js-sdk/js-sdk-components/proof/proof.md"
      - Example: "js-sdk/js-sdk-example.md"
      - Browser Wallet Demo: "js-sdk/js-sdk-browser-wallet-demo.md"
  - FAQ:
      - Overview: "https://support.polygon.technology/support/solutions/82000473421"
# If you declare plugins, you need to declare all of them,
# including search (which would otherwise have been installed by default.)
plugins:
  - search
  - mermaid2
  - mkdocs-video

extra:
  analytics:
    provider: custom
    property: GTM-5TKTB44
