site_name: Polygon ID Documentation tutorials

site_url: https://polygon.technology/polygon-id/
theme:
  name: material
  palette:
    primary: deep purple
  logo: logo-white.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


nav:
  - Issuer:
    - Overview: "issuer/issuer-overview.md"
    - Platform API:
      - Introduction: "issuer/platform-api/introduction.md"
      - Make Your First Request: "issuer/platform-api/make-your-first-request.md"
      - API Reference: 
        - Onboarding Organization:
          - Introduction: "issuer/platform-api/onboarding-orgs/introduction.md"
          - API: "issuer/platform-api/onboarding-orgs/apis.md"
        - Issuer:
          - Introduction: "issuer/platform-api/issuer/introduction.md"
          - API: "issuer/platform-api/issuer/apis.md"
        - Claim Schemas:
          - Introduction: "issuer/platform-api/schemas/introduction.md"
          - API: "issuer/platform-api/schemas/apis.md"
        - Claim Offers:
          - Introduction: "issuer/platform-api/offers/introduction.md"
          - API: "issuer/platform-api/offers/apis.md" 
      - API Flow Tutorial:  
          - Onboarding Organization Tutorial: "issuer/platform-api/flow-tutorial/onboarding-org-flow-tutorial.md"   
          - Create Schema Tutorial: "issuer/platform-api/flow-tutorial/create-schema-flow-tutorial.md"     
          - Issue Claim Tutorial: "issuer/platform-api/flow-tutorial/issue-claim-flow-tutorial.md"     
  - Verifier:
    - Overview: "verifier/verifier-overview.md"
    - Off-chain Verification:
      - Introduction: "verifier/verification-library/verifier-library-intro.md"
      - APIs: 
        - Config: "verifier/verification-library/config.md"
        - Auth Request: "verifier/verification-library/request-api-guide.md"
        - Verification: "verifier/verification-library/verification-api-guide.md"
        - JWZ: "verifier/verification-library/jwz.md"
      - Run a Verifier: "verifier/verification-library/verifier-set-up.md"
    - On-chain Verification:
      - Implement ERC20 zk airdrop in 20 minutes: "verifier/on-chain-verification/overview.md"
    - ZK Query Language : "verifier/verification-library/zk-query-language.md"
  - Wallet: 
    - Overview: "wallet/wallet-overview.md"
    
    # - Wallet SDK: 
    #   - Flutter SDK: "wallet/wallet-sdk/flutter-sdk.md"
    #   - Example App: "wallet/wallet-sdk/example-app.md"
    #   - PolygonId SDK Plugin: "wallet/wallet-sdk/polygonid-sdk-plugin.md"
    # - Types of Wallets: 
    #   - Identity Wallet:
    #     - Create Identity: "wallet/types-of-wallets/identity-wallet/create-identity.md"
    #     - Sign and Authenticate: "wallet/types-of-wallets/identity-wallet/sign-and-authenticate.md"
    #   - Credential Wallet: 
    #     - Fetch and Save Claims: "wallet/types-of-wallets/credential-wallet/fetch-and-save-claims.md"
    # - Proof Generation:
    #     - Overview: "wallet/proof-generation/proof-generation-overview.md"
    #     - Types of Requests and Proofs: "wallet/proof-generation/types-of-auth-requests-and-proofs.md"
    #     - JWZ: "wallet/proof-generation/json-web-zero-knowledge.md"  
    
  - Smart Contracts: 
    - Overview: "contracts/overview.md"
  
# If you declare plugins, you need to declare all of them, 
# including search (which would otherwise have been installed by default.)
plugins:
  - search
  - mermaid2
