site_name: Polygon ID Documentation tutorials

site_url: https://polygon.technology/polygon-id/
theme:
  name: material
  palette:
    primary: deep purple
  logo: logo-white.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


nav:
  - Issuer Protocol:
    - Introduction: "getting-started/getting-started.md"
    - Baby Jubjub Keypair: "getting-started/babyjubjub.md"
    - Sparse Merkle Tree: "getting-started/mt.md"
    - Claim: 
      - Generic Claim: "getting-started/claim/generic-claim.md"
      - Auth Claim: "getting-started/claim/auth-claim.md"
      - Claim Schema: "getting-started/claim/claim-schema.md"
    - Identity: 
      - Identity Structure: "getting-started/identity/identity-structure.md"
      - Identity State: "getting-started/identity/identity-state.md"
      - Identifier: "getting-started/identity/identifier.md"
    - State Transition: 
      - Overview: "getting-started/state-transition/overview.md"
      - Add Claim to the Claims Tree: "getting-started/state-transition/new-identity-state.md"
      - Generate Proof for State Transition: "getting-started/state-transition/state-transition-proof.md"
      - Verify the Proof On-Chain: "getting-started/state-transition/on-chain-state-transition.md"
  - Verifier Intergration: 
    - Introduction: "verify-with-zkp-application-level/intro.md"
    - ZK login workflow: "verify-with-zkp-application-level/zk-login-workflow.md"
    - ZK login integration: "verify-with-zkp-application-level/zk-login-integration.md"
    - Demo: "verify-with-zkp-application-level/demo.md"
    - JWZ: "verify-with-zkp-application-level/jwz.md"
    - Query: "verify-with-zkp-application-level/query-language.md"
  - Circuits:
    - Main Circuits: "circuits/main-circuits.md"
    - Template Circuits: "circuits/template-circuits.md"
  - Contracts: 
    - Overview: "contracts/overview.md"


# If you declare plugins, you need to declare all of them, 
# including search (which would otherwise have been installed by default.)
plugins:
  - search
  - mermaid2
