site_name: Polygon ID Documentation tutorials

site_url: https://polygon.technology/polygon-id/
theme:
  name: material
  palette:
    primary: deep purple
  logo: logo-white.svg
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.tabs.link
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - mkdocs_graphviz
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - Home: "index.md"
  - Issuer:
    - Overview: "issuer/issuer-overview.md"
    - Platform API:
      - Introduction: "issuer/platform-api/introduction.md"
      - Getting Started: "issuer/platform-api/flow-tutorial/happy-path.md"
      - API Reference: 
        - Onboarding Organization: "issuer/platform-api/onboarding-orgs/apis.md"
        - Issuer: "issuer/platform-api/issuer/apis.md"
        - Claim Schemas: "issuer/platform-api/schemas/apis.md"
        - Claim Offers: "issuer/platform-api/offers/apis.md" 
  - Verifier:
    - Overview: "verifier/verifier-overview.md"
    - Off-chain Verification:
      - Introduction: "verifier/verification-library/verifier-library-intro.md"
      - APIs: 
        - Config: "verifier/verification-library/config.md"
        - ZK Request APIs: "verifier/verification-library/request-api-guide.md"
        - Verification APIs: "verifier/verification-library/verification-api-guide.md"
      - Tutorial - Run a Verifier: "verifier/verification-library/verifier-set-up.md"
    - On-chain Verification:
      - Implement ERC20 zk airdrop in 20 minutes: "verifier/on-chain-verification/overview.md"
    - ZK Query Language : "verifier/verification-library/zk-query-language.md"
  - Wallet: 
    - Overview: "wallet/wallet-overview.md"
    - Identity:
      - Overview: "wallet/identity/identity-wallet-overview.md"
      - APIs:
        - Overview: "wallet/identity/api/api-overview.md"
        - Create Identity: "wallet/identity/api/create-identity.md"
        - Get Identity: "wallet/identity/api/get-identity.md"
        - Get Identities: "wallet/identity/api/get-identities.md"
        - Remove Identity: "wallet/identity/api/remove-identity.md"
        - Restore Identity: "wallet/identity/api/restore-identity.md"
        - Sign Message: "wallet/identity/api/sign.md"
    - Credential: 
      - Overview: "wallet/credential/credential-overview.md"
      - APIs: 
        - Overview: "wallet/credential/api/api-overview.md"
        - Get Claims: "wallet/credential/api/get-claims.md"
        - Fetch and Save Claims: "wallet/credential/api/fetch-and-save-claims.md"
        - Update Claims: "wallet/credential/api/update-claims.md"
        - Remove Claims: "wallet/credential/api/remove-claims.md"
    - Proof:
      - Overview: "wallet/proof/proof-generation-overview.md"
      - APIs: 
        - Overview: "wallet/proof/api/api-overview.md"
        - Generate Proof: "wallet/proof/api/prove.md"
    - Iden3comm:
      - Overview: "wallet/iden3comm/iden3comm-overview.md"
      - Auth Requests: "wallet/iden3comm/auth-requests.md"
      - JWZ: "wallet/iden3comm/jwz.md"
      - APIs: 
        - Authenticate: "wallet/iden3comm/apis/authenticate.md"
        - Get Proof: "wallet/iden3comm/apis/get-proofs.md"
        - Get Vocabulary: "wallet/iden3comm/apis/get-vocabs.md"
        - Get Iden3 Message: "wallet/iden3comm/apis/iden3-message.md"
    - Wallet SDK:
      - Flutter SDK:
        - Overview: "wallet/wallet-sdk/flutter-sdk/flutter-sdk-overview.md"
        - Install Flutter SDK: "wallet/wallet-sdk/flutter-sdk/install-flutter-sdk.md"
        - Build App with SDK: "wallet/wallet-sdk/flutter-sdk/build-app-with-flutter-sdk.md"
      - Polygon ID Wallet SDK:
        - Overview: "wallet/wallet-sdk/polygonid-sdk/polygonid-sdk-overview.md"
        - Polygon ID SDK Plugin: "wallet/wallet-sdk/polygonid-sdk/polygonid-sdk-plugin.md"
        - Example App: "wallet/wallet-sdk/polygonid-sdk/example-app.md"

    



    # - Wallet SDK: 
    #   - Flutter SDK: "wallet/wallet-sdk/flutter-sdk.md"
    #   - Example App: "wallet/wallet-sdk/example-app.md"
    #   - PolygonId SDK Plugin: "wallet/wallet-sdk/polygonid-sdk-plugin.md"
    # - Types of Wallets: 
    #   - Identity Wallet:
    #     - Create Identity: "wallet/types-of-wallets/identity-wallet/create-identity.md"
    #     - Sign and Authenticate: "wallet/types-of-wallets/identity-wallet/sign-and-authenticate.md"
    #   - Credential Wallet: 
    #     - Fetch and Save Claims: "wallet/types-of-wallets/credential-wallet/fetch-and-save-claims.md"
    # - Proof Generation:
    #     - Overview: "wallet/proof-generation/proof-generation-overview.md"
    #     - Types of Requests and Proofs: "wallet/proof-generation/types-of-auth-requests-and-proofs.md"
    #     - JWZ: "wallet/proof-generation/json-web-zero-knowledge.md"  
    
  - Smart Contracts: 
    - Overview: "contracts/overview.md"
  
# If you declare plugins, you need to declare all of them, 
# including search (which would otherwise have been installed by default.)
plugins:
  - search
  - mermaid2
